# Generated by Django 5.2.8 on 2025-11-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kf_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='video_file',
            field=models.FileField(blank=True, help_text='Загрузите видеофайл для этого контента', null=True, upload_to='media_content_videos/', verbose_name='Видеофайл'),
        ),
    ]
