# Generated by Django 5.2.8 on 2025-11-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kf_app', '0002_mediacontent_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='video_file',
            field=models.FileField(blank=True, help_text='Загрузите видеофайл для этого эпизода', null=True, upload_to='episode_videos/', verbose_name='Видеофайл эпизода'),
        ),
    ]
