# Generated by Django 5.2.8 on 2025-11-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kf_app', '0003_episode_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediacontent',
            name='video_file',
        ),
    ]
