# Generated by Django 5.2.8 on 2025-11-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kf_app', '0004_remove_mediacontent_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediacontent',
            name='video_file',
            field=models.FileField(blank=True, help_text='Загрузите видеофайл (для фильмов)', null=True, upload_to='media_content_videos/', verbose_name='Видеофайл'),
        ),
    ]
